// Class: ReadFDA_GA
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : FDA::FDA_GA
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.04/02       [394242]
Creator        : geonmo
Date           : Thu Sep 10 17:32:11 2015
Host           : Linux lcgapp-slc6-x86-64-21.cern.ch 2.6.32-504.23.4.el6.x86_64 #1 SMP Wed Jun 10 07:47:59 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/geonmo/bdt2
Training events: 1200
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
Formula: "(0)+(1)*x0+(2)*x1+(3)*x2+(4)*x3" [The discrimination formula]
ParRanges: "(-1,1);(-10,10);(-10,10);(-10,10);(-10,10)" [Parameter ranges]
FitMethod: "GA" [Optimisation Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Converger: "None" [FitMethod uses Converger to improve result]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
jpsi_pt                       jpsi_pt                       jpsi_pt                       jpsi_pt                                                         'F'    [0.0862565487623,255.842895508]
jpsi_eta                      jpsi_eta                      jpsi_eta                      jpsi_eta                                                        'F'    [-2.90122294426,4.39363384247]
jpsi_phi                      jpsi_phi                      jpsi_phi                      jpsi_phi                                                        'F'    [-3.13265371323,3.14061498642]
jpsi_lxy                      jpsi_lxy                      jpsi_lxy                      jpsi_lxy                                                        'F'    [0.000311450130539,9.4537191391]
jpsi_vProb                    jpsi_vProb                    jpsi_vProb                    jpsi_vProb                                                      'F'    [6.28686336768e-07,0.998821258545]
jpsi_dca                      jpsi_dca                      jpsi_dca                      jpsi_dca                                                        'F'    [3.24249267578e-05,0.0498838424683]
jpsi_muID                     jpsi_muID                     jpsi_muID                     jpsi_muID                                                       'I'    [1,3]
jpsi_trackQuality             jpsi_trackQuality             jpsi_trackQuality             jpsi_trackQuality                                               'I'    [1,7]
jpsi_minJetDR                 jpsi_minJetDR                 jpsi_minJetDR                 jpsi_minJetDR                                                   'F'    [6.31332513876e-05,4.67943429947]
jpsi_minBJetDR                jpsi_minBJetDR                jpsi_minBJetDR                jpsi_minBJetDR                                                  'F'    [6.31332513876e-05,5.26783037186]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadFDA_GA : public IClassifierReader {

 public:

   // constructor
   ReadFDA_GA( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFDA_GA" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "jpsi_pt", "jpsi_eta", "jpsi_phi", "jpsi_lxy", "jpsi_vProb", "jpsi_dca", "jpsi_muID", "jpsi_trackQuality", "jpsi_minJetDR", "jpsi_minBJetDR" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'I';
      fType[7] = 'I';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFDA_GA() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fParameter[5];
};

inline void ReadFDA_GA::Initialize() 
{
   fParameter[0] = 0.437020454833535;
   fParameter[1] = 0.000657437905416502;
   fParameter[2] = 0;
   fParameter[3] = -0.00164863633804861;
   fParameter[4] = 0.227600289415891;
}

inline double ReadFDA_GA::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   // interpret the formula
   double retval = fParameter[0]+fParameter[1]*inputValues[0]+fParameter[2]*inputValues[1]+fParameter[3]*inputValues[2]+fParameter[4]*inputValues[3];

   return retval; 
}

// Clean up
inline void ReadFDA_GA::Clear() 
{
   // nothing to clear
}
   inline double ReadFDA_GA::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
