// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.04/02       [394242]
Creator        : geonmo
Date           : Thu Sep 10 17:33:11 2015
Host           : Linux lcgapp-slc6-x86-64-21.cern.ch 2.6.32-504.23.4.el6.x86_64 #1 SMP Wed Jun 10 07:47:59 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/geonmo/bdt2
Training events: 1200
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
jpsi_pt                       jpsi_pt                       jpsi_pt                       jpsi_pt                                                         'F'    [0.0862565487623,255.842895508]
jpsi_eta                      jpsi_eta                      jpsi_eta                      jpsi_eta                                                        'F'    [-2.90122294426,4.39363384247]
jpsi_phi                      jpsi_phi                      jpsi_phi                      jpsi_phi                                                        'F'    [-3.13265371323,3.14061498642]
jpsi_lxy                      jpsi_lxy                      jpsi_lxy                      jpsi_lxy                                                        'F'    [0.000311450130539,9.4537191391]
jpsi_vProb                    jpsi_vProb                    jpsi_vProb                    jpsi_vProb                                                      'F'    [6.28686336768e-07,0.998821258545]
jpsi_dca                      jpsi_dca                      jpsi_dca                      jpsi_dca                                                        'F'    [3.24249267578e-05,0.0498838424683]
jpsi_muID                     jpsi_muID                     jpsi_muID                     jpsi_muID                                                       'I'    [1,3]
jpsi_trackQuality             jpsi_trackQuality             jpsi_trackQuality             jpsi_trackQuality                                               'I'    [1,7]
jpsi_minJetDR                 jpsi_minJetDR                 jpsi_minJetDR                 jpsi_minJetDR                                                   'F'    [6.31332513876e-05,4.67943429947]
jpsi_minBJetDR                jpsi_minBJetDR                jpsi_minBJetDR                jpsi_minBJetDR                                                  'F'    [6.31332513876e-05,5.26783037186]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "jpsi_pt", "jpsi_eta", "jpsi_phi", "jpsi_lxy", "jpsi_vProb", "jpsi_dca", "jpsi_muID", "jpsi_trackQuality", "jpsi_minJetDR", "jpsi_minBJetDR" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'I';
      fType[7] = 'I';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.06232822477262;
   fWeightMatrix0to1[1][0] = 2.1510009411302;
   fWeightMatrix0to1[2][0] = 2.02342747327141;
   fWeightMatrix0to1[3][0] = 1.80980414609615;
   fWeightMatrix0to1[4][0] = -2.57318161120031;
   fWeightMatrix0to1[5][0] = -1.0153815597904;
   fWeightMatrix0to1[6][0] = 0.0859443605211245;
   fWeightMatrix0to1[7][0] = 2.44299653932197;
   fWeightMatrix0to1[8][0] = -0.318814058883321;
   fWeightMatrix0to1[9][0] = -1.23585503980936;
   fWeightMatrix0to1[10][0] = -3.66490945618506;
   fWeightMatrix0to1[11][0] = -0.239913702525608;
   fWeightMatrix0to1[12][0] = -1.28411887573575;
   fWeightMatrix0to1[13][0] = 0.269091250406981;
   fWeightMatrix0to1[14][0] = -2.17114354236489;
   fWeightMatrix0to1[0][1] = 1.11364960298986;
   fWeightMatrix0to1[1][1] = -0.456319426840979;
   fWeightMatrix0to1[2][1] = 1.84168490040944;
   fWeightMatrix0to1[3][1] = 0.2011573337173;
   fWeightMatrix0to1[4][1] = 2.80780452796825;
   fWeightMatrix0to1[5][1] = 0.350860440597941;
   fWeightMatrix0to1[6][1] = -4.6406985873375;
   fWeightMatrix0to1[7][1] = 0.94311741379172;
   fWeightMatrix0to1[8][1] = 0.10459118893177;
   fWeightMatrix0to1[9][1] = 0.66461880302145;
   fWeightMatrix0to1[10][1] = -1.29134193078334;
   fWeightMatrix0to1[11][1] = 0.871231545481582;
   fWeightMatrix0to1[12][1] = -3.07959564003553;
   fWeightMatrix0to1[13][1] = -2.00651048084523;
   fWeightMatrix0to1[14][1] = 0.705323302888692;
   fWeightMatrix0to1[0][2] = 0.308240659508776;
   fWeightMatrix0to1[1][2] = 1.53526759414792;
   fWeightMatrix0to1[2][2] = 0.331754510924053;
   fWeightMatrix0to1[3][2] = -0.111402789055152;
   fWeightMatrix0to1[4][2] = 0.0035455949626424;
   fWeightMatrix0to1[5][2] = 0.500363972062009;
   fWeightMatrix0to1[6][2] = -0.296862455939363;
   fWeightMatrix0to1[7][2] = 1.36131852427075;
   fWeightMatrix0to1[8][2] = 0.0557442321028908;
   fWeightMatrix0to1[9][2] = -0.119411411949603;
   fWeightMatrix0to1[10][2] = 0.13292433048754;
   fWeightMatrix0to1[11][2] = 1.36218446046385;
   fWeightMatrix0to1[12][2] = 1.22828389714252;
   fWeightMatrix0to1[13][2] = 1.39707926407691;
   fWeightMatrix0to1[14][2] = 0.511916211913754;
   fWeightMatrix0to1[0][3] = -1.5855932602082;
   fWeightMatrix0to1[1][3] = 1.08769183217227;
   fWeightMatrix0to1[2][3] = -0.0691962756340759;
   fWeightMatrix0to1[3][3] = 1.86258626759642;
   fWeightMatrix0to1[4][3] = 1.07566234240633;
   fWeightMatrix0to1[5][3] = 1.71618739669163;
   fWeightMatrix0to1[6][3] = 3.98894414824181;
   fWeightMatrix0to1[7][3] = -1.92834704518398;
   fWeightMatrix0to1[8][3] = 7.28807957411947;
   fWeightMatrix0to1[9][3] = 0.527051222683612;
   fWeightMatrix0to1[10][3] = -2.96528690257023;
   fWeightMatrix0to1[11][3] = -1.03634613309827;
   fWeightMatrix0to1[12][3] = -1.22742502112465;
   fWeightMatrix0to1[13][3] = 1.97762106863274;
   fWeightMatrix0to1[14][3] = 1.64448255972993;
   fWeightMatrix0to1[0][4] = -2.20719987139109;
   fWeightMatrix0to1[1][4] = 0.293423337489653;
   fWeightMatrix0to1[2][4] = -1.3864670157274;
   fWeightMatrix0to1[3][4] = 0.861490241040306;
   fWeightMatrix0to1[4][4] = 0.442770486037273;
   fWeightMatrix0to1[5][4] = -0.64896895143163;
   fWeightMatrix0to1[6][4] = -0.231500751065197;
   fWeightMatrix0to1[7][4] = -1.10822902908941;
   fWeightMatrix0to1[8][4] = -0.387317714619048;
   fWeightMatrix0to1[9][4] = -1.34301680869248;
   fWeightMatrix0to1[10][4] = -0.211129932553948;
   fWeightMatrix0to1[11][4] = -1.66094739178035;
   fWeightMatrix0to1[12][4] = 0.261863446966199;
   fWeightMatrix0to1[13][4] = 0.110151145217618;
   fWeightMatrix0to1[14][4] = 3.24683879576152;
   fWeightMatrix0to1[0][5] = -0.236516345248029;
   fWeightMatrix0to1[1][5] = -1.49026236245202;
   fWeightMatrix0to1[2][5] = -0.270172268356321;
   fWeightMatrix0to1[3][5] = 1.16675649164808;
   fWeightMatrix0to1[4][5] = 1.79996514294519;
   fWeightMatrix0to1[5][5] = 2.00517554882099;
   fWeightMatrix0to1[6][5] = -0.625925661184909;
   fWeightMatrix0to1[7][5] = 0.389781730434913;
   fWeightMatrix0to1[8][5] = -0.330323219858097;
   fWeightMatrix0to1[9][5] = -5.62242357878618;
   fWeightMatrix0to1[10][5] = -0.376889656208355;
   fWeightMatrix0to1[11][5] = 1.38326857805734;
   fWeightMatrix0to1[12][5] = -0.0411371390170585;
   fWeightMatrix0to1[13][5] = -2.42199368871332;
   fWeightMatrix0to1[14][5] = 1.3335311177346;
   fWeightMatrix0to1[0][6] = -0.847526706748328;
   fWeightMatrix0to1[1][6] = -0.228745846506955;
   fWeightMatrix0to1[2][6] = 1.70599733548753;
   fWeightMatrix0to1[3][6] = -1.55561006957924;
   fWeightMatrix0to1[4][6] = -1.00080813471736;
   fWeightMatrix0to1[5][6] = 0.990082279587099;
   fWeightMatrix0to1[6][6] = -0.438633336177118;
   fWeightMatrix0to1[7][6] = -2.05942233616583;
   fWeightMatrix0to1[8][6] = -1.10539115047362;
   fWeightMatrix0to1[9][6] = -0.0854338302446859;
   fWeightMatrix0to1[10][6] = -0.253943607039875;
   fWeightMatrix0to1[11][6] = -1.49651828932235;
   fWeightMatrix0to1[12][6] = 0.523053198885018;
   fWeightMatrix0to1[13][6] = 1.48747292064056;
   fWeightMatrix0to1[14][6] = -1.28401266228158;
   fWeightMatrix0to1[0][7] = 1.63625229596514;
   fWeightMatrix0to1[1][7] = -1.27920399074487;
   fWeightMatrix0to1[2][7] = 0.0931653021100812;
   fWeightMatrix0to1[3][7] = -0.382505258890592;
   fWeightMatrix0to1[4][7] = -0.231353106114797;
   fWeightMatrix0to1[5][7] = -2.35078391760216;
   fWeightMatrix0to1[6][7] = 0.817872517323534;
   fWeightMatrix0to1[7][7] = 0.178129242327987;
   fWeightMatrix0to1[8][7] = 4.03128222782792;
   fWeightMatrix0to1[9][7] = -1.56098508211582;
   fWeightMatrix0to1[10][7] = 0.307891468025397;
   fWeightMatrix0to1[11][7] = 1.05604781090977;
   fWeightMatrix0to1[12][7] = -1.32877668307927;
   fWeightMatrix0to1[13][7] = 1.16980822315766;
   fWeightMatrix0to1[14][7] = -2.43052092976708;
   fWeightMatrix0to1[0][8] = -1.80218263598933;
   fWeightMatrix0to1[1][8] = 0.585201657915714;
   fWeightMatrix0to1[2][8] = 0.5574927971684;
   fWeightMatrix0to1[3][8] = 1.6255880312961;
   fWeightMatrix0to1[4][8] = 2.16214121459278;
   fWeightMatrix0to1[5][8] = -0.418465518708766;
   fWeightMatrix0to1[6][8] = -0.855527991794075;
   fWeightMatrix0to1[7][8] = 0.17910389126349;
   fWeightMatrix0to1[8][8] = -0.886451046799393;
   fWeightMatrix0to1[9][8] = 0.723699887737586;
   fWeightMatrix0to1[10][8] = 3.75547919467522;
   fWeightMatrix0to1[11][8] = -1.52948483357986;
   fWeightMatrix0to1[12][8] = 0.123901929925416;
   fWeightMatrix0to1[13][8] = -1.22889297272788;
   fWeightMatrix0to1[14][8] = -0.253140347160131;
   fWeightMatrix0to1[0][9] = 0.85378935099023;
   fWeightMatrix0to1[1][9] = 1.85574021071774;
   fWeightMatrix0to1[2][9] = -2.75671234682412;
   fWeightMatrix0to1[3][9] = 0.202501731845955;
   fWeightMatrix0to1[4][9] = 1.5829504959711;
   fWeightMatrix0to1[5][9] = 1.99600391375674;
   fWeightMatrix0to1[6][9] = 0.874641921022262;
   fWeightMatrix0to1[7][9] = -1.33565291096068;
   fWeightMatrix0to1[8][9] = 0.231745879440064;
   fWeightMatrix0to1[9][9] = -0.0917483739219979;
   fWeightMatrix0to1[10][9] = 4.15751981300323;
   fWeightMatrix0to1[11][9] = 2.53263984071511;
   fWeightMatrix0to1[12][9] = -0.612139477708637;
   fWeightMatrix0to1[13][9] = 0.978595099076627;
   fWeightMatrix0to1[14][9] = 1.23730607537514;
   fWeightMatrix0to1[0][10] = -1.10957201476044;
   fWeightMatrix0to1[1][10] = 0.358370881585111;
   fWeightMatrix0to1[2][10] = 2.26594866179035;
   fWeightMatrix0to1[3][10] = -0.637651979196622;
   fWeightMatrix0to1[4][10] = 0.571755685750676;
   fWeightMatrix0to1[5][10] = -0.734408408462137;
   fWeightMatrix0to1[6][10] = 0.81059750126371;
   fWeightMatrix0to1[7][10] = 0.140533163923163;
   fWeightMatrix0to1[8][10] = 3.5220768947526;
   fWeightMatrix0to1[9][10] = -2.55425887162113;
   fWeightMatrix0to1[10][10] = 1.49207852870097;
   fWeightMatrix0to1[11][10] = 0.937472684726037;
   fWeightMatrix0to1[12][10] = 0.328975464727013;
   fWeightMatrix0to1[13][10] = 0.593627336771385;
   fWeightMatrix0to1[14][10] = -0.49630820478854;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 2.74567645458453;
   fWeightMatrix1to2[0][1] = -0.486192592581795;
   fWeightMatrix1to2[0][2] = 2.83611629878902;
   fWeightMatrix1to2[0][3] = -1.4660280954278;
   fWeightMatrix1to2[0][4] = 2.67635676381713;
   fWeightMatrix1to2[0][5] = 2.6600153039161;
   fWeightMatrix1to2[0][6] = 3.06684181426695;
   fWeightMatrix1to2[0][7] = -1.16990685994544;
   fWeightMatrix1to2[0][8] = 4.68769491260922;
   fWeightMatrix1to2[0][9] = 3.8642999824489;
   fWeightMatrix1to2[0][10] = -2.9411127659125;
   fWeightMatrix1to2[0][11] = 1.19778627539978;
   fWeightMatrix1to2[0][12] = -1.9311491601563;
   fWeightMatrix1to2[0][13] = 1.75508863214333;
   fWeightMatrix1to2[0][14] = -4.52923629868561;
   fWeightMatrix1to2[0][15] = -1.51083522762759;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 1.14960587025;
   fMax_1[0][0] = 150.316253662;
   fMin_1[1][0] = 0.0862565487623;
   fMax_1[1][0] = 255.842895508;
   fMin_1[2][0] = 0.0862565487623;
   fMax_1[2][0] = 255.842895508;
   fMin_1[0][1] = -2.40134167671;
   fMax_1[0][1] = 2.46363854408;
   fMin_1[1][1] = -2.90122294426;
   fMax_1[1][1] = 4.39363384247;
   fMin_1[2][1] = -2.90122294426;
   fMax_1[2][1] = 4.39363384247;
   fMin_1[0][2] = -3.13265371323;
   fMax_1[0][2] = 3.12646579742;
   fMin_1[1][2] = -3.13104081154;
   fMax_1[1][2] = 3.14061498642;
   fMin_1[2][2] = -3.13265371323;
   fMax_1[2][2] = 3.14061498642;
   fMin_1[0][3] = 0.00162253191229;
   fMax_1[0][3] = 4.53289985657;
   fMin_1[1][3] = 0.000311450130539;
   fMax_1[1][3] = 9.4537191391;
   fMin_1[2][3] = 0.000311450130539;
   fMax_1[2][3] = 9.4537191391;
   fMin_1[0][4] = 6.28686336768e-07;
   fMax_1[0][4] = 0.998300790787;
   fMin_1[1][4] = 1.57013744229e-06;
   fMax_1[1][4] = 0.998821258545;
   fMin_1[2][4] = 6.28686336768e-07;
   fMax_1[2][4] = 0.998821258545;
   fMin_1[0][5] = 3.24249267578e-05;
   fMax_1[0][5] = 0.0472183227539;
   fMin_1[1][5] = 7.65323638916e-05;
   fMax_1[1][5] = 0.0498838424683;
   fMin_1[2][5] = 3.24249267578e-05;
   fMax_1[2][5] = 0.0498838424683;
   fMin_1[0][6] = 1;
   fMax_1[0][6] = 3;
   fMin_1[1][6] = 1;
   fMax_1[1][6] = 3;
   fMin_1[2][6] = 1;
   fMax_1[2][6] = 3;
   fMin_1[0][7] = 3;
   fMax_1[0][7] = 7;
   fMin_1[1][7] = 1;
   fMax_1[1][7] = 7;
   fMin_1[2][7] = 1;
   fMax_1[2][7] = 7;
   fMin_1[0][8] = 6.31332513876e-05;
   fMax_1[0][8] = 4.3077788353;
   fMin_1[1][8] = 0.000965833722148;
   fMax_1[1][8] = 4.67943429947;
   fMin_1[2][8] = 6.31332513876e-05;
   fMax_1[2][8] = 4.67943429947;
   fMin_1[0][9] = 6.31332513876e-05;
   fMax_1[0][9] = 4.3077788353;
   fMin_1[1][9] = 0.000965833722148;
   fMax_1[1][9] = 5.26783037186;
   fMin_1[2][9] = 6.31332513876e-05;
   fMax_1[2][9] = 5.26783037186;
   fMin_1[0][10] = 3.00532150269;
   fMax_1[0][10] = 3.19942736626;
   fMin_1[1][10] = 3.0007174015;
   fMax_1[1][10] = 3.19995856285;
   fMin_1[2][10] = 3.0007174015;
   fMax_1[2][10] = 3.19995856285;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
